env 설정
mash-up-kr/node-11th-toy-mashupAlpineClub pull request #18
Opened 2021-09-12 12:22 UTC by turastory

- .gitignore에 env 관련 파일 조건을 추가하고 기존 .env.local 파일을 삭제했습니다.
- .env와 ConfigService를 사용해 포트를 적용합니다. 환경 변수 PORT가 정의되어 있지 않은 경우 기본값으로 3000을 할당했습니다.

2021-09-12 12:47 UTC, kor-Chipmunk requested changes
포트 작업해주셔서 감사합니다~
오류 일어나는 부분은 아래 답글로 적었습니다.

`develop` 브랜치로부터 rebase 가 안되어있어서, 제가 작업해 놓은 것들이 보였네요.
rebase 진행하면서 conflict 해결한 커밋 로그들 포스 푸쉬 했습니다.
다음에는 rebase 부탁드려욥~

2021-09-12 12:47 UTC, kor-Chipmunk commented on src/config/configuration.ts
> +  port: +get('PORT') ?? 3000,
`PORT` 값이 없을 시 `+get('PORT')` 의 값이 NaN 이 되어버려 기본값이 설정이 안되네요..! `+` 기호를 삭제하는 게 좋을 것 같습니다.

```suggestion
  port: get('PORT') ?? 3000,
```

2021-09-13 04:23 UTC, turastory commented on src/config/configuration.ts
> +  port: +get('PORT') ?? 3000,
이렇게 하면 포트가 number이거나 string이어서 문제가 될 것 같았는데 `app.listen()` 함수가 포트를 두 가지 타입으로 받네요. 문제 없을 것 같습니다.

2021-09-14 14:54 UTC, kor-Chipmunk approved these changes
LGTM!

2021-09-24 22:43 UTC, merged